apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-friends-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-friends
  template:
    metadata:
      labels:
        app: virtual-friends
    spec:
      containers:
      - name: virtual-friends-app
        image: gcr.io/ysong-chat/brain-go:f523b26-a60ce2e8
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: FLASK_PORT
            value: "8085"
          - name: ENV_STR
            value: "prod"
          - name: LOG_LEVEL
            value: "warn"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
            ephemeral-storage: "2Gi"
          limits:
            memory: "2Gi"
            cpu: "2"
            ephemeral-storage: "4Gi"
      - name: virtual-friend-py-sidecar
        image: gcr.io/ysong-chat/flask-app:f523b26-e1b3da61
        ports:
        - containerPort: 8085
        env:
          - name: PORT
            value: "8085"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
            ephemeral-storage: "2Gi"
            # nvidia.com/gpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
            ephemeral-storage: "4Gi"
            # nvidia.com/gpu: "1"
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "present"
        effect: "NoSchedule"
#      nodeSelector:
#        nvidia.com/gpu: present
