apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-friends-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-friends
  template:
    metadata:
      labels:
        app: virtual-friends
    spec:
      containers:
      - name: virtual-friends-app
        image: gcr.io/ysong-chat/brain-go:d924379-e0f55772
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
            ephemeral-storage: "2Gi"
          limits:
            memory: "2Gi"
            cpu: "2"
            ephemeral-storage: "4Gi"
      - name: virtual-friend-py-sidecar
        image: gcr.io/ysong-chat/brain-py-sidecar:d924379-d7bb8ea7
        ports:
        - containerPort: 8085
        env:
          - name: PORT
            value: "8085"
        resources:
          requests:
            memory: "10Gi"
            cpu: "2"
            ephemeral-storage: "10Gi"
            nvidia.com/gpu: "1"
          limits:
            memory: "10Gi"
            cpu: "2"
            ephemeral-storage: "10Gi"
            nvidia.com/gpu: "1"
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "present"
        effect: "NoSchedule"
#      nodeSelector:
#        nvidia.com/gpu: present
